import SummonerDetail from "@/components/SummonerDetail";
import { getSummonerByName, getSummonerMatches, Summoner } from "@/helpers/api";
import Head from "next/head";

export async function getServerSideProps({
  params,
}: {
  params: { summonerName: string };
}) {
  const { summonerName } = params;
  const [summoner, error] = await getSummonerByName(summonerName);

  if (summoner) {
    const [stats, error] = await getSummonerMatches(summoner, 1);
    return { props: { summoner, error, stats } };
  }

  return { props: { summoner, error: error } };
}

export default function Home({
  summoner,
  stats,
  error,
}: {
  summoner?: Summoner;
  stats?: any;
  error?: string;
}) {
  const title = summoner?.name ? `${summoner.name} | LOL Stats` : "LOL Stats";

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="p-5">
        {stats}
        {error}
        {summoner ? <SummonerDetail {...{ summoner }} /> : error}
      </main>
    </>
  );
}
